export const ADD_INGREDEINTS = 'ADD_INGREDEINTS';
export const REM_INGREDEINTS = 'REM_INGREDEINTS';
export const SET_INGREDEINTS = 'SET_INGREDEINTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const BURGER_PURCHASE_SUCCESS = 'BURGER_PURCHASE_SUCCESS';
export const BURGER_PURCHASE_FAILED = 'BURGER_PURCHASE_FAILED';
export const BURGER_PURCHASE_START = 'BURGER_PURCHASE_START';
export const BURGER_PURCHASING_INIT = 'BURGER_PURCHASING_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const LOGOUT = 'LOGOUT';

export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH';
